-- Memory map for patched Pokemon Emerald ROM
-- Generated by ROM Comparison Tool

local MemoryMap = {
    -- Data locations in ROM
    pokemonStats = 0x08324E04,
    moveData = 0x083211F0,
    gameCode = 0x080000AC,
    gameName = 0x080000A0,
    typeNames = 0x0831AE38,
    abilityNames = 0x0831B6DB,
    
    -- Use these addresses in your Memory.lua module
    -- Example: local pokemonData = Memory.read_u8(MemoryMap.pokemonStats)
}

return MemoryMap